language: php

sudo: false

php:
    - "5.6"
    - "7.0"
    - "nightly"

env:
    global:
        - PQ_DSN="postgres://postgres@localhost/test"

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

services: postgresql

install:
    - composer install
    - psql -U postgres -c "CREATE DATABASE test"
    - cp _setup.inc-dist _setup.inc

script: ./bin/phpunit tests/
